---
title: "visualization I"
author: "Bohan Zhu"
date: "2025-09-25"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
```


```{r}
library(p8105.datasets)

data(weather_df)
```

```{r}
ggplot(data = weather_df, mapping = aes(x = tmin, y = tmax))+
  geom_point()
```

```{r}
ggp_weather_scatterplot =
  weather_df |> 
  ggplot(data = weather_df, mapping = aes(x = tmin, y = tmax))+
  geom_point()

ggp_weather_scatterplot
```

check that some rows are missing
```{r}
weather_df |> 
  filter(is.na(tmax))
```

## Fancier scatterplots

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color= name, size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE)
```

use faceting real quick

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color= name), alpha = 0.3, size = 0.8)+
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)


weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color= name), alpha = 0.3, size = 0.8)+
  geom_smooth(se = FALSE) +
  facet_grid(name ~ .)
```

let's make a somewhat more interesting scatterplot
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color= name, shape = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE)+
  facet_grid(. ~name)
```

LA plot: 
```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax_fahr = tmax * (9 / 5) +32,
    tmin_fahr = tmin * (9 / 5) +32
  ) |> 
  ggplot(aes ( x = tmin_fahr, tmax_fahr))+
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE)
```

## small things

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color= name, shape = name)) +
  #geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE)

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color= name, shape = name)) +
  geom_smooth(se = FALSE)+
  geom_point()

```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax))+
  geom_hex()
```

```{r}
weather_df |> 
  ggplot(aes(x =tmin, y = tmax))+
  geom_point(color = "purple")
```

## Univariateplots

```{r}
weather_df |> 
  ggplot(aes(x =tmin))+
  geom_histogram(color = "white", fill = "red")
```

```{r}
weather_df |> 
  ggplot(aes (x= tmin, color = name))+
  geom_histogram()

weather_df |> 
  ggplot(aes (x= tmin, fill = name))+
  geom_histogram()
```

how would I fix this? maybe facet?
```{r}
weather_df |> 
  ggplot(aes (x= tmin, fill = name))+
  geom_histogram() +
  facet_grid(name ~.)

weather_df |> 
  ggplot(aes (x= tmin, fill = name))+
  geom_density(alpha = 0.2)
```

```{r}
weather_df |> 
  ggplot(aes( x = name, y =tmin))+
  geom_boxplot(aes(fill = name))
```

violin plots
```{r}

```

